### ISSUE TITLE
Missing NPM Package

### ISSUE THREAD

**Issue by Snyaundi** [alextyers/period-tracker-app-whitelabelled#3]
Hello, I am part of a team working on customizing the Oky application for Swahili speaking countries. We are unable to complete the UI build as the code is missing some NPM package (see attached screenshot) 

Please guide us on how to proceed. Thank you.
![missing_library_oky](https://user-images.githubusercontent.com/64415048/135106038-3bb81221-c789-4f72-810b-37243e7e720b.png)

**Comment by ankitbansal-gc** [comment]
@Snyaundi I see you are trying to use npm instead of yarn package manger. Can you please follow the steps mentioned in the readme using yarn and also please note this project uses monorepo so it makes use of yarn workspaces too.

**Comment by Snyaundi** [comment]
Thank you!
